[pytest]
<<<<<<< HEAD
testpaths = runners
python_files = *_runner.py test_*.py
python_classes = Test*
python_functions = test_* run_*
addopts = -v --tb=short
=======
addopts = 
    --html=reports/report.html 
    --self-contained-html 
    -v 
    -s
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
>>>>>>> 4a18db9 (Initial commit: Completed Selenium Pytest Automation Suite for PLT Courses)
